<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,0,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,2,1,'5L2c5ZOB5qyj6LWP');
$cfg_Cs[3]=array(0,1,0,'5pyA5paw5Yqo5oCB');
$cfg_Cs[4]=array(0,1,1,'5pyN5Yqh5oql5Lu3');
$cfg_Cs[5]=array(0,1,0,'6IGU57O75oiR5Lus');
$cfg_Cs[6]=array(0,1,0,'5rS75Yqo5YaF5a65');
$cfg_Cs[7]=array(0,1,1,'5Yqg55uf55u45YWz');
$cfg_Cs[8]=array(2,2,1,'5YaF5pmv5ama57qx5L2c5ZOB');
$cfg_Cs[9]=array(2,2,1,'5aSW5pmv5L2c5ZOB5qyj6LWP');
$cfg_Cs[10]=array(2,2,1,'6auY56uv5ama57qx5pGE5b2x');
?>