<div>
										  										<a href="[field:arcurl/]" tppabs="[field:arcurl/]" title="[field:title/]" target="_blank">
										                        <img src="[field:litpic/]" tppabs="[field:litpic/" alt="[field:title/]" width="155" height="155"/>
										                        <span><b>[field:title/]</b></span><i>[field:pubdate/]</i>
										  										</a>
										</div>
                    <!-- <div>[field:imglink/]</div> -->