<ul>
                <li>[field:textlink/]<span style=" float:right; margin-right:60px;">([field:pubdate function=MyDate('m-d',@me)/])</span></li>
                <li>[field:textlink/]<span style=" float:right; margin-right:60px;">([field:pubdate function=MyDate('m-d',@me)/])</span></li>
                <li>[field:textlink/]<span style=" float:right; margin-right:60px;">([field:pubdate function=MyDate('m-d',@me)/])</span></li>
                <li>[field:textlink/]<span style=" float:right; margin-right:60px;">([field:pubdate function=MyDate('m-d',@me)/])</span></li>
                <li>[field:textlink/]<span style=" float:right; margin-right:60px;">([field:pubdate function=MyDate('m-d',@me)/])</span></li>
                <li>[field:textlink/]</li>
                 <li>[field:textlink/]</li>
                  <li>[field:textlink/]</li>
                   <li>[field:textlink/]</li>
                    <li>[field:textlink/]</li>
                     <li>[field:textlink/]</li>
                      <li>[field:textlink/]</li>
                       <li>[field:textlink/]</li>
                        <li>[field:textlink/]</li>
               </ul>