<?php
$z[0]=Array("global","",42,74);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",102,134);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("arclist","\r\n      <div>\r\n        <a href=\"[field:arcurl/]\" tppabs=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">\r\n          <img src=\"[field:litpic/]\" tppabs=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"195\" height=\"195\"/>\r\n        </a>\r\n      </div>\r\n      ",276,573);
$z[2][4]['row']="5";
$z[3]=Array("global","",1061,1093);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1121,1153);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("arclist","\r\n    <li><i>[field:ID/]</i><span> [field:textlink/]</span></li>\r\n    ",1232,1351);
$z[5][4]['typeid']="3";
$z[5][4]['row']="9";

?>