<?php
$z[0]=Array("include","",172,210);
$z[0][4]['filename']="ny_head.htm";
$z[1]=Array("include","",240,279);
$z[1][4]['filename']="ny_toper.htm";
$z[2]=Array("include","",285,328);
$z[2][4]['filename']="ny_main_menu.htm";
$z[3]=Array("field","",481,510);
$z[3][4]['name']="position";
$z[4]=Array("global","",703,735);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("channel","\r\n                <li>\r\n                <a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a>\r\n                </li>\r\n                ",850,1043);
$z[5][4]['type']="son";
$z[5][4]['typeid']="2";
$z[6]=Array("include","",1098,1144);
$z[6][4]['filename']="ny_left_content.htm";
$z[7]=Array("global","",1262,1294);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("field","",1406,1426);
$z[8][4]['name']="litpic";
$z[9]=Array("field","",1443,1462);
$z[9][4]['name']="title";
$z[10]=Array("field","",1504,1523);
$z[10][4]['name']="title";
$z[11]=Array("field","",1594,1644);
$z[11][4]['name']="pubdate";
$z[11][4]['function']="MyDate('Y-m-d',@me)";
$z[12]=Array("field","\r\n                <li>\r\n                <a href=\"[field:imgsrc/]\" class=\"group4\">\r\n                  <img src='[field:imgsrc/]' alt=\"[field:alttext/]\"/>\r\n                </a>\r\n                </li>\r\n                ",2075,2352);
$z[12][4]['name']="imgurls";
$z[12][4]['alt']="图片输出区";
$z[13]=Array("prenext","",2511,2536);
$z[13][4]['get']="pre";
$z[14]=Array("prenext","",2629,2655);
$z[14][4]['get']="next";
$z[15]=Array("include","",2785,2825);
$z[15][4]['filename']="ny_footer.htm";

?>