<?php
$z[0]=Array("include","",170,208);
$z[0][4]['filename']="ny_head.htm";
$z[1]=Array("include","",719,758);
$z[1][4]['filename']="ny_toper.htm";
$z[2]=Array("include","",764,807);
$z[2][4]['filename']="ny_main_menu.htm";
$z[3]=Array("field","",959,988);
$z[3][4]['name']="position";
$z[4]=Array("global","",1481,1513);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1542,1574);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",1689,1735);
$z[6][4]['filename']="ny_left_content.htm";
$z[7]=Array("global","",1853,1885);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1916,1948);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("list","\r\n                <li>\r\n                <a href=\"[field:arcurl/]\" tppabs=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">\r\n                  <img src=\"[field:litpic/]\" tppabs=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"155\" height=\"155\"/>\r\n                  <span><b>[field:title/]</b></span>\r\n                  <i>[field:pubdate function=MyDate('Y-m-d',@me)/]</i>\r\n                </a>\r\n                </li>\r\n                ",2068,2542);
$z[9][4]['pagesize']="6";
$z[10]=Array("pagelist","",2673,2744);
$z[10][4]['listitem']="info,index,end,pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",3091,3131);
$z[11][4]['filename']="ny_footer.htm";

?>