<?php
$z[0]=Array("global","",768,800);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",1669,1701);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",3364,3396);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",4257,4289);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",8132,8164);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",10110,10142);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",18321,18353);
$z[6][4]['name']="cfg_templets_skin";

?>